### ISSUE TITLE
Numpy failing to find libgfortran

### ISSUE THREAD

**Issue by traleig1** [nix-community/talon-nix#1]
I'm seeing this error in talon.log:
```2022-10-15 19:53:44  INFO Activating Microphone: "Tiger Lake-LP Smart Sound Technology Audio Controller Digital Microphone"
2022-10-15 19:53:44    IO Traceback (most recent call last):
2022-10-15 19:53:44    IO   File "lib/python3.9/site-packages/numpy/core/__init__.py", line 23, in <module>
2022-10-15 19:53:44    IO   File "lib/python3.9/site-packages/numpy/core/multiarray.py", line 10, in <module>
2022-10-15 19:53:44    IO   File "lib/python3.9/site-packages/numpy/core/overrides.py", line 6, in <module>
2022-10-15 19:53:44    IO ImportError: libgfortran-040039e1.so.5.0.0: cannot open shared object file: No such file or directory
2022-10-15 19:53:44    IO During handling of the above exception, another exception occurred:
2022-10-15 19:53:44    IO Traceback (most recent call last):
2022-10-15 19:53:44    IO   File "app/resources/loader.py", line 153, in <module>
2022-10-15 19:53:44    IO   File "talon/__init__.py", line 88, in <module>
2022-10-15 19:53:44    IO   File "talon/__init__.py", line 65, in init
2022-10-15 19:53:44    IO   File "talon/track/system.py", line 30, in __init__
2022-10-15 19:53:44    IO   File "talon/usb.py", line 26, in <module>
2022-10-15 19:53:44    IO   File "talon/track/tobii.py", line 13, in <module>
2022-10-15 19:53:44    IO   File "talon/track/filter.py", line 2, in <module>
2022-10-15 19:53:44    IO   File "lib/python3.9/site-packages/numpy/__init__.py", line 140, in <module>
2022-10-15 19:53:44    IO   File "lib/python3.9/site-packages/numpy/core/__init__.py", line 49, in <module>
2022-10-15 19:53:44    IO ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.9 from "/nix/store/gvislax7kxly72vhc7k69mfn8lzcj8n2-talon-0.3.1/bin/resources/python/bin/python3"
  * The NumPy version is: "1.23.1"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: libgfortran-040039e1.so.5.0.0: cannot open shared object file: No such file or directory
2022-10-15 19:53:44    IO
```

It does seem to be packaged, though, at:
`$out/bin/resources/python/lib/python3.9/site-packages/numpy.libs/libgfortran-040039e1.so.5.0.0`

**Comment by adisbladis** [comment]
I'm also seeing this but I haven't seen anything else fail because of this error.

I don't quite understand why as we set `LD_LIBRARY_PATH` to include ` $out/bin/resources/python/lib/python3.9/site-packages/numpy.libs/libgfortran-040039e1.so.5.0.0` in the wrapper.

**Comment by qbit** [comment]
On my system the wrapped `talon` script, `LD_LIBRARY_PATH`  is missing the `numpy.libs` directory. I was also unable to get things working without adding it manually.
